# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-TextHighlight
version:      1.0.2
version_from: TextHighlight.pm
installdirs:  site
requires:
    Syntax::Highlight::Perl:       0
    Tk:                            800.024

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
